const cors={'access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...cors}});
const num=v=>Number(v||0);
const pct=(now,old)=>old>0?((now-old)/old)*100:(now>0?100:0);
const clamp=(v,min,max)=>Math.min(max,Math.max(min,v));
function signalScore({today,d1,d3,d7,videos,commission,reviews}){
  const g1=pct(today,d1),g3=pct(today,d3),g7=pct(today,d7);
  const momentum=clamp(g1,0,120)/120*30+clamp(g3,0,250)/250*20+clamp(g7,0,500)/500*10;
  const acceleration=clamp(g1-g3/3,0,120)/120*15;
  const competition=20-clamp(videos,0,60)/60*20;
  const money=clamp(commission,0,15)/15*3;
  const freshness=2-clamp(Math.log10(Math.max(1,reviews)),0,4)/4*2;
  const score=Math.round(clamp(momentum+acceleration+competition+money+freshness,0,100));
  const early=score>=62&&videos<=20&&g3>15;
  const decision=score>=70?'hot':score>=45?'watch':'skip';
  return{score,decision,early_signal:early,growth_1d:g1,growth_3d:g3,growth_7d:g7,acceleration:g1-g3/3};
}
async function history(db,id,limit=8){const {results}=await db.prepare(`SELECT snapshot_date,sales,reviews,videos,captured_at FROM trend_snapshots WHERE product_id=? ORDER BY snapshot_date DESC,id DESC LIMIT ?`).bind(id,limit).all();return results||[];}
async function enriched(db,p){const h=await history(db,p.id,8);const latest=h[0]||{};const byDays=(n)=>h.find((_,i)=>i>=n)||h[h.length-1]||{};const s=signalScore({today:num(latest.sales),d1:num(byDays(1).sales),d3:num(byDays(3).sales),d7:num(byDays(7).sales),videos:num(latest.videos),commission:num(p.commission),reviews:num(latest.reviews)});return{...p,queue:!!p.queue,snapshot_date:latest.snapshot_date||null,sales_today:num(latest.sales),sales_prev:num(byDays(1).sales),reviews:num(latest.reviews),videos:num(latest.videos),history:h,...s};}
async function list(db){const {results}=await db.prepare(`SELECT * FROM trend_products ORDER BY updated_at DESC`).all();return Promise.all((results||[]).map(p=>enriched(db,p)));}
async function upsertSnapshot(db,b){const id=b.id||crypto.randomUUID();const date=b.snapshot_date||new Date().toISOString().slice(0,10);if(!b.name&&!b.id)throw Error('NAME_REQUIRED');await db.prepare(`INSERT INTO trend_products(id,name,category,price,url,commission,queue,updated_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET name=COALESCE(NULLIF(excluded.name,''),trend_products.name),category=excluded.category,price=excluded.price,url=excluded.url,commission=excluded.commission,updated_at=CURRENT_TIMESTAMP`).bind(id,b.name||'',b.category||'',num(b.price),b.url||'',num(b.commission),b.queue?1:0).run();await db.prepare(`INSERT INTO trend_snapshots(product_id,snapshot_date,sales,reviews,videos) VALUES(?,?,?,?,?) ON CONFLICT(product_id,snapshot_date) DO UPDATE SET sales=excluded.sales,reviews=excluded.reviews,videos=excluded.videos,captured_at=CURRENT_TIMESTAMP`).bind(id,date,num(b.sales_today??b.sales),num(b.reviews),num(b.videos)).run();return{id,date};}
export default{async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const u=new URL(req.url);if(u.pathname==='/health')return json({ok:true,service:'trend-hunter',d1:!!env.TREND_DB,signals:'1d-3d-7d'});if(u.pathname==='/api/trends/snapshots'&&req.method==='POST'){try{const b=await req.json();const rows=Array.isArray(b)?b:b.items;if(!Array.isArray(rows)||!rows.length)return json({ok:false,error:'ITEMS_REQUIRED'},400);const out=[];for(const row of rows)out.push(await upsertSnapshot(env.TREND_DB,row));return json({ok:true,updated:out.length,items:out});}catch(e){return json({ok:false,error:e?.message||'UNKNOWN'},500);}}
if(u.pathname!=='/api/trends')return json({ok:false,error:'NOT_FOUND'},404);try{if(req.method==='GET'){const items=await list(env.TREND_DB);return json({ok:true,items,meta:{count:items.length,hot:items.filter(x=>x.decision==='hot').length,early:items.filter(x=>x.early_signal).length}});}if(req.method==='POST')return json({ok:true,...await upsertSnapshot(env.TREND_DB,await req.json())});if(req.method==='PATCH'){const b=await req.json();if(!b.id)return json({ok:false,error:'ID_REQUIRED'},400);if(typeof b.queue==='boolean')await env.TREND_DB.prepare(`UPDATE trend_products SET queue=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(b.queue?1:0,b.id).run();return json({ok:true});}if(req.method==='DELETE'){const id=u.searchParams.get('id');if(!id)return json({ok:false,error:'ID_REQUIRED'},400);await env.TREND_DB.prepare(`DELETE FROM trend_snapshots WHERE product_id=?`).bind(id).run();await env.TREND_DB.prepare(`DELETE FROM trend_products WHERE id=?`).bind(id).run();return json({ok:true});}return json({ok:false,error:'METHOD_NOT_ALLOWED'},405);}catch(e){return json({ok:false,error:e?.message||'UNKNOWN'},500);}}};