name = "shopee-trend-hunter"
main = "worker.js"
compatibility_date = "2026-09-05"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "TREND_DB"
database_name = "shopee-trend-hunter-db"
database_id = "c4a4a397-8194-4be5-9c62-e79670ea3151"
